services:
  gameoflifeapi:
    build:
      context: ./GameOfLifeApi
      dockerfile: Dockerfile
    image: gameoflifeapi:latest
    container_name: gameoflifeapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - golivedata:/app/App_Data
  tests:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    working_dir: /src
    volumes:
      - ./:/src
    command: >
      bash -lc "
      echo '--- ls ---' && ls -la &&
      echo '--- csprojs ---' && find . -maxdepth 2 -name '*.csproj' &&
      dotnet restore ./GameOfLifeApi/GameOfLifeApi.csproj &&
      dotnet restore ./GameOfLifeApi.Tests/GameOfLifeApi.Tests.csproj &&
      dotnet test ./GameOfLifeApi.Tests/GameOfLifeApi.Tests.csproj
      "

volumes:
  golivedata:
    driver: local
