services:
  gameoflifeapi:
    build:
      context: ./GameOfLifeApi
      dockerfile: Dockerfile
    image: gameoflifeapi:latest
    container_name: gameoflifeapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - golivedata:/app/App_Data
  unit-tests:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    working_dir: /src
    volumes:
      - ./:/src
    command: >
      bash -lc "
      dotnet restore ./GameOfLifeApi/GameOfLifeApi.csproj &&
      dotnet restore ./GameOfLifeApi.Tests/GameOfLifeApi.Tests.csproj &&
      dotnet test ./GameOfLifeApi.Tests/GameOfLifeApi.Tests.csproj --filter \"Category!=Integration\"
      "

  integration-tests:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    working_dir: /src
    volumes:
      - ./:/src
    command: >
      bash -lc "
      dotnet restore ./GameOfLifeApi/GameOfLifeApi.csproj &&
      dotnet restore ./GameOfLifeApi.Tests/GameOfLifeApi.Tests.csproj &&
      dotnet test ./GameOfLifeApi.Tests/GameOfLifeApi.Tests.csproj --filter \"Category=Integration\"
      "

volumes:
  golivedata:
    driver: local
